# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Leland Jefferis
email: jefferis.l@gmail.com
author: Leland Jefferis
description: > # this means to ignore newlines until "baseurl:"
             Documentation and blog posts centered around Leland's programming projects. Take a look around and enjoy your stay!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  lixiaolan
linkedin_username: leland-jefferis-49929189

# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
